spring:
  application:
    name: gateway-zuul
server:
  port: 5555
zuul:
  routes:
    api-a:
      path: /api-a/**
      #url: http://localhost:8081/test1/
      serviceId: server-one
    api-b:
      path: /api-b/**
      serviceId: server-two
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 6000
  add-host-header: true
  sensitive-headers:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
feign:
  hystrix:
    enabled: true